export const stuffILike = [
    "universell utforming",
    "terrengsykling",
    "Lego",
    "å spille dataspill",
    "hunder",
    "katter",
    "å lage mat",
    "å diskutere arkitektur",
    "å gå tur",
    "å lage gode brukeropplevelser",
    "å optimalisere",
    "å dele kunnskap",
    "å teste ut ny teknologi",
    "å utfordre det etablerte",
    "designsystemer",
    "å programmere",
    "progressive enhancement (sjekk ut denne siden uten JavaScript)",
    "samarbeid",
    "å klatre",
    "å fiske",
    "elvepadling",
    "å stå på ski",
    "ikke Monopol",
    "en god utvikleropplevelse",
];
